<a href="https://colab.research.google.com/github/krishnakanthkona-3110/Python_Journey/blob/main/Python_Life_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
  #A pandas series is like a column in a table

In [ ]:
s1=pd.Series([1,2,3,4,5,6])
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:

s2=pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e','f'])
print(s2)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [ ]:








s3 = pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e','f'],dtype='float')
print(s3)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
dtype: float64

In [ ]:

s4=pd.Series({'a':1,'b':2,'c':3},dtype='str')
s4

a    1
b    2
c    3
dtype: object

In [ ]:

d1 = pd.DataFrame([1,2,3,4,5])
print(d1)

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:


d2 = pd.DataFrame([[1,2,3],[4,5,6]])
d2

   0  1  2
0  1  2  3
1  4  5  6

In [ ]:
d2=pd.DataFrame(s2)
print(d2)

   0
a  1
b  2
c  3
d  4
e  5
f  6

In [ ]:
d3=pd.DataFrame([[1,2,3],[3,4,5]],columns=['a','b','c'])
d3

   a  b  c
0  1  2  3
1  3  4  5

In [ ]:
d4=pd.DataFrame([[1,2,3],[3,4,5],[7,8,9]],columns=['a','b','c'],index=['columns','v','f'])
d4

         a  b  c
columns  1  2  3
v        3  4  5
f        7  8  9

In [ ]:

dic = [{'ali':1,'bhai':2},{'ema':10,'kai':9},{'ema':11,'kai':15}]
d5=pd.DataFrame(dic,index=['a','b','c'])
d5

   ali  bhai   ema   kai
a  1.0   2.0   NaN   NaN
b  NaN   NaN  10.0   9.0
c  NaN   NaN  11.0  15.0

In [ ]:

d3

   a  b  c
0  1  2  3
1  3  4  5

In [ ]:
 print(d3['a'])
 print(d3['b'])

0    1
1    3
Name: a, dtype: int64
0    2
1    4
Name: b, dtype: int64

In [ ]:
d3['d']=d3['a']*d3['b']
d3['e']=d3['a']*d3['d']

In [ ]:
d3

   a  b  c   d   e
0  1  2  3   2   2
1  3  4  5  12  36

In [ ]:
pop = d3.pop('b')

KeyError: 'b'

In [ ]:
pop

0    2
1    4
Name: b, dtype: int64

In [ ]:
d3

   a  c   d   e
0  1  3   2   2
1  3  5  12  36

In [ ]:
del d3['d']

In [ ]:

d3

   a  c   e
0  1  3   2
1  3  5  36

In [ ]:

d3.insert(1,'new',d3['c']) #location, column, data

In [ ]:
d3

   a  new  c   e
0  1    3  3   2
1  3    5  5  36

In [ ]:
d3.insert(1,'del',pop)

In [ ]:
d3

   a  del  new  c   e
0  1    2    3  3   2
1  3    4    5  5  36

In [ ]:
 d=[{'a':10,'del':10,'new':10,'c':10,'e':10}]
 d=pd.DataFrame(d)
 df11=pd.concat([d3,d],ignore_index=True)
 df11

    a  del  new   c   e
0   1    2    3   3   2
1   3    4    5   5  36
2  10   10   10  10  10

In [ ]:
d

    a  del  new   c   e
0  10   10   10  10  10

In [ ]:
n1=[{'a':1,'b':2,'c':3,'d':4,'e':5},{'s':1}]
n1=pd.DataFrame(n1)
n1

     a    b    c    d    e    s
0  1.0  2.0  3.0  4.0  5.0  NaN
1  NaN  NaN  NaN  NaN  NaN  1.0

In [ ]:
import numpy as np

In [ ]:
n2 = pd.DataFrame({'abc':np.random.randint(2,6,10),'bcd':np.random.randint(1,5,10)},)
n2

   abc  bcd
0    3    2
1    4    4
2    4    3
3    3    1
4    4    1
5    4    4
6    2    1
7    4    1
8    4    3
9    4    4

In [ ]:
print(n2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     10 non-null     int64
 1   bcd     10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes
None

In [ ]:
n2.describe()

             abc        bcd
count  10.000000  10.000000
mean    3.600000   2.400000
std     0.699206   1.349897
min     2.000000   1.000000
25%     3.250000   1.000000
50%     4.000000   2.500000
75%     4.000000   3.750000
max     4.000000   4.000000

In [ ]:
print(n2.loc[9,'abc'])

4

In [ ]:
n2.loc[2:6,['abc']]

   abc
2    4
3    3
4    4
5    4
6    2

In [ ]:
n2.loc[[1,2,3,5],['abc','bcd']]

   abc  bcd
1    4    4
2    4    3
3    3    1
5    4    4

In [ ]:
n2.loc[1:2,['abc','bcd']]

   abc  bcd
1    4    4
2    4    3

In [ ]:
n2.iloc[9,1]

np.int64(4)

In [ ]:
n2.iloc[9,0]

np.int64(4)

In [ ]:
n2.iloc[0:10,0:2]

   abc  bcd
0    3    2
1    4    4
2    4    3
3    3    1
4    4    1
5    4    4
6    2    1
7    4    1
8    4    3
9    4    4

In [ ]:
n2.abc

0    3
1    4
2    4
3    3
4    4
5    4
6    2
7    4
8    4
9    4
Name: abc, dtype: int64

In [ ]:
n2.abc.values

array([3, 4, 4, 3, 4, 4, 2, 4, 4, 4])

In [ ]:
n2['sub']=n2.abc.values-n2.bcd.values
n2

   abc  bcd  sub
0    3    2    1
1    4    4    0
2    4    3    1
3    3    1    2
4    4    1    3
5    4    4    0
6    2    1    1
7    4    1    3
8    4    3    1
9    4    4    0

In [ ]:
a=[['rk',102,1500],['ram',103,2000],['sita',100,1000]]
df1=pd.DataFrame(a,columns=['emp','id','sal'],index=['columns','a','s'])
df1

          emp   id   sal
columns    rk  102  1500
a         ram  103  2000
s        sita  100  1000

In [ ]:
 y=df1[df1.sal>=1500]
 print(y)
 y[['id','sal']]

         emp   id   sal
columns   rk  102  1500
a        ram  103  2000

          id   sal
columns  102  1500
a        103  2000

In [ ]:
y['id']

columns    102
a          103
Name: id, dtype: int64

In [ ]:
df1

          emp   id   sal
columns    rk  102  1500
a         ram  103  2000
s        sita  100  1000

In [ ]:
new_row = pd.DataFrame([{'emp':'jithu','id':105,'sal':1800}])

In [ ]:
df1 = pd.concat([df1,new_row],ignore_index=True)
df1

     emp   id   sal
0     rk  102  1500
1    ram  103  2000
2   sita  100  1000
3  jithu  105  1800

In [ ]:
new = pd.DataFrame([{'emp':'prasad','id':105,'sal':np.nan}])
df1= pd.concat([df1,new],ignore_index=True)
df1

      emp   id     sal
0      rk  102  1500.0
1     ram  103  2000.0
2    sita  100  1000.0
3   jithu  105  1800.0
4  prasad  105     NaN

In [ ]:
df1.isnull()

     emp     id    sal
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False   True

In [ ]:
df1.isnull().sum()

emp    0
id     0
sal    1
dtype: int64

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   emp     5 non-null      object
 1   id      5 non-null      int64
 2   sal     4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

In [ ]:
print('2'*10)

2222222222

In [ ]:
df1

      emp   id     sal
0      rk  102  1500.0
1     ram  103  2000.0
2    sita  100  1000.0
3   jithu  105  1800.0
4  prasad  105     NaN

In [ ]:
k = df1.dropna()
k

     emp   id     sal
0     rk  102  1500.0
1    ram  103  2000.0
2   sita  100  1000.0
3  jithu  105  1800.0

In [ ]:
df1

      emp   id     sal
0      rk  102  1500.0
1     ram  103  2000.0
2    sita  100  1000.0
3   jithu  105  1800.0
4  prasad  105     NaN

In [ ]:
df1.fillna(value='1')

      emp   id     sal
0      rk  102  1500.0
1     ram  103  2000.0
2    sita  100  1000.0
3   jithu  105  1800.0
4  prasad  105       1

In [ ]:
df1.drop([1],axis=0,inplace=True)
#df1

In [ ]:
df1

      emp   id     sal
0      rk  102  1500.0
2    sita  100  1000.0
3   jithu  105  1800.0
4  prasad  105     NaN

In [ ]:
#l = df1.drop([0,3],axis=0,inplace=True)
l

In [ ]:
df1

    id  sal
4  105  NaN

In [ ]:
df1.drop(['emp'],axis=1,inplace=True)

In [ ]:
df1

    id     sal
0  102  1500.0
3  105  1800.0
4  105     NaN

In [ ]:
df1.drop('sal',axis=1)

    id
0  102
3  105
4  105

In [ ]:
df1.drop(['id'],axis=1)

      sal
0  1500.0
3  1800.0
4     NaN

In [ ]:
df1

    id     sal
0  102  1500.0
3  105  1800.0
4  105     NaN

In [ ]:
df1.loc[3,['id','sal']]

id      105.0
sal    1800.0
Name: 3, dtype: float64

In [ ]:
df1.iloc[:,:]

    id     sal
0  102  1500.0
3  105  1800.0
4  105     NaN

In [ ]:
df1.drop([6])

KeyError: '[6] not found in axis'

In [ ]:
df = pd.DataFrame([['Falcon',300],['Falcon',100],['parrot',12],['parrot',20]],columns=['Animal','rate'])

In [ ]:
df

   Animal  rate
0  Falcon   300
1  Falcon   100
2  parrot    12
3  parrot    20

In [ ]:
df.groupby(['Animal']).mean()

         rate
Animal
Falcon  200.0
parrot   16.0

In [ ]:
df.groupby(['Animal']).mean()

         rate
Animal
Falcon  200.0
parrot   16.0

In [ ]:
pd.DataFrame({'Animal': ['Falcon','Falcon','Parrot','Parrot'],'Rate':[100,12,123, 1223]})

   Animal  Rate
0  Falcon   100
1  Falcon    12
2  Parrot   123
3  Parrot  1223